In [1]:
0.041092764047644406import pandas as pd

In [2]:
bases = pd.read_csv("~/sudosequence_genomics_hackathon/Challenge 1/bams/bases.csv", sep='\t', 
                  names = ["Bases"])

In [3]:
q_values = pd.read_csv("~/sudosequence_genomics_hackathon/Challenge 1/bams/q_values.csv", sep='\t', 
                  names = ["Q Values"])

In [4]:
pos = pd.read_csv("~/sudosequence_genomics_hackathon/Challenge 1/bams/position.csv", sep='\t', 
                  names = ["Position"])

In [5]:
bases1=bases[18000000:19000000] #keep relevant 10^6

In [6]:
q1=q_values[18000000:19000000] #keep relevant 10^6

In [7]:
pos1=pos[18000000:19000000] #keep relevant 10^6

In [33]:
pos3=pos1[997000:]

In [37]:
q3=q1[997000:]

In [57]:
def asciitodecimal(string):
    string1=[ord(c) for c in string]
    return string1

In [58]:

q3['Q Values'] = q3['Q Values'].apply(asciitodecimal)

TypeError: ord() expected string of length 1, but int found

In [66]:
def dectop(array):
    array1=[10**(-((c-33)/10)) for c in array]
    return array1

In [67]:
q3['Q Values'] = q3['Q Values'].apply(dectop)

/Users/sujay/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [73]:
def maxkeeper(array):
    maxq=max(array)
    return maxq

In [74]:
q3['Q Values'] = q3['Q Values'].apply(maxkeeper)

/Users/sujay/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [81]:
q3

          Q Values
18997000  0.000501
18997001  0.006310
18997002  0.000501
18997003  0.000501
18997004  0.000501
18997005  0.000501
18997006  0.001995
18997007  0.031623
18997008  0.001995
18997009  0.000501
18997010  0.000501
18997011  0.000501
18997012  0.000501
18997013  0.031623
18997014  0.000501
18997015  0.000501
18997016  0.000501
18997017  0.251189
18997018  0.006310
18997019  0.251189
18997020  0.000501
18997021  0.001995
18997022  0.000501
18997023  0.000501
18997024  0.251189
18997025  0.000501
18997026  0.000501
18997027  0.000501
18997028  0.000501
18997029  0.006310
...            ...
18999970  0.031623
18999971  0.000501
18999972  0.000501
18999973  0.000501
18999974  0.000501
18999975  0.001995
18999976  0.006310
18999977  0.001995
18999978  0.031623
18999979  0.000501
18999980  0.000501
18999981  0.000501
18999982  0.000501
18999983  0.251189
18999984  0.000501
18999985  0.000501
18999986  0.000501
18999987  0.251189
18999988  0.031623
18999989  0.000501
18999990  0.000501
18999991  0.001995
18999992  0.000501
18999993  0.000501
18999994  0.000501
18999995  0.031623
18999996  0.000501
18999997  0.251189
18999998  0.031623
18999999  0.000501

[3000 rows x 1 columns]

In [78]:
q3["Q Values"].mean()

0.05940955800159703

In [79]:
q_values21 = pd.read_csv("~/sudosequence_genomics_hackathon/Challenge 1/bams/q_values21.csv", sep='\t', 
                  names = ["Q Values"])

In [80]:
pos21 = pd.read_csv("~/sudosequence_genomics_hackathon/Challenge 1/bams/position21.csv", sep='\t', 
                  names = ["Position"])

In [95]:
pos211=pos21[19050000:19053000]

In [96]:
pos211

          Position
19050000  32078970
19050001  32078977
19050002  32078987
19050003  32078991
19050004  32078991
19050005  32078993
19050006  32078994
19050007  32078997
19050008  32078997
19050009  32079002
19050010  32079002
19050011  32079004
19050012  32079005
19050013  32079016
19050014  32079017
19050015  32079019
19050016  32079022
19050017  32079028
19050018  32079043
19050019  32079048
19050020  32079050
19050021  32079050
19050022  32079051
19050023  32079051
19050024  32079063
19050025  32079065
19050026  32079067
19050027  32079089
19050028  32079092
19050029  32079094
...            ...
19052970  32352146
19052971  32352146
19052972  32352146
19052973  32352146
19052974  32352146
19052975  32352146
19052976  32352149
19052977  32352149
19052978  32352151
19052979  32352151
19052980  32352152
19052981  32352152
19052982  32352152
19052983  32352153
19052984  32352153
19052985  32352153
19052986  32352153
19052987  32352153
19052988  32352153
19052989  32352153
19052990  32352153
19052991  32352153
19052992  32352153
19052993  32352153
19052994  32352153
19052995  32352154
19052996  32352156
19052997  32352156
19052998  32352156
19052999  32352156

[3000 rows x 1 columns]

In [97]:
q21=q_values21[19050000:19053000]

In [98]:
q21

                                                   Q Values
19050000  BBBFFFFFFFFFFIIIIIFIIIIIIFFIIIIIIIIIIIIIIIIIII...
19050001  BB<BFFFFB<BB<BF<B<FFBBBFBBFFBFFFFB7BBFFB770BBF...
19050002  BBBFFFFFFFFFFFFFFFIFFFFIIIFIFIIFIIIFFFFII0<BBF...
19050003  BBBFBFFFFFFFFIIIIIIIIIIIIIIFFFIIIIIIFIIFIIIIII...
19050004  0<<BFFFFFBBFFFFFFFBFBFF<B0BBBBFFFBF7BFFBFFFFB<...
19050005  BBBFFFFFFFFFFIIIIIIIIIIIIIIIIIIIIFIIFIBFFIIIII...
19050006  BBBFFFFFFFFFFIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII...
19050007  BBBFFFFFFFFFFIIIIIIIIFIIIIIIIFFFFFFFFFIIIIII<F...
19050008  BBBFFFBFFFFFFFFFFFBBFFFFFFBFFIFFBBBFFBFFFFFFFF...
19050009  BBBFFFFFFFFFFIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFFF...
19050010  BBBFFFFFFFFFFIIIFFIIFFFFIIIBFIIIIIIFFFFIIIFFBF...
19050011  BBBFFFFFFFFFFIIIIIIIIIIIIIIFIIIIIIIIIIIIIBFFIF...
19050012  BBBFFFFFFFFFFIFIIIIIIIIIIFFIIFIII7FFFIIIFFIIII...
19050013  BBBFFFFFFFFFFFBFFFFFIFFFFFIFFFBFIIIFFFIIIIIIIF...
19050014  BBBFFFFFFFFFFFFIFFBFIIIIFFII<FFFFFFFFIFFFIIIII...
19050015  BBBFFFFFFFFFFIIIIIIIIIIIIIFFIIFIIFIIIIIIIIIIII...
19050016  BBBFFFFFFFFFFIIIIIIIIIIFFIIFIIIIIIIIIIIIIIIIII...
19050017  BBBFFFFFFFBBF<<BF<BFFB<FFBFIIIFIFFBFIBFIIIBF<7...
19050018  B<0<FBFFFFFFFFIFIBFFI<BFBBFFFBFFFIFFIIFFFFIF<F...
19050019  BBBFFFFFFFFFFIIIIIIIIIIIIIIIIIFIFIIIIIIIIIIIII...
19050020  BBBFFFFFFFFFFI<BFFFFBFBBFFFFFFBFBFBBFFFFFFIFIF...
19050021  BBBFFFFBFBFFFII<BFFBFBFFBFFBBBBFF<F<<BFFB<BBFB...
19050022  0<BFBBF<F<BBFFFFI<FFB0B<FBBBFBF7B<FF77<0B70BBF...
19050023  BBBFFFFFFFFFFIIIIIIII<FBFIFIIIFIIIIFIIIIIFFIFI...
19050024  BBBFFFFFFFFFFIIFFFIIIIIIIIIIIIIIIIIIIIIIIIIFII...
19050025  BBB0BFFFFFFBBFFBFIFIIIIIIIIFBFBFFBFIFIBFFIFFF7...
19050026  BBBFFFFFFFFFFFFFFFIIIIIIIIBFFFFIIIIIIIFIIIIIII...
19050027  BBBFFFFFFFFFFIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFFI...
19050028  BBBFFFFFFFFFBFFFFFFFIFFBFFF<FFFFFIFFFFIFFFIIFF...
19050029  7<<BFBF<BFFFFBBFB<BBBBBF<7BBFFFFFFFFBFBFFFFBFF...
...                                                     ...
19052970  BFFIFFFFFBBFIIIFFFFFFFFFFIFIFIIIIIIIIFFFFFBFFB...
19052971  FIFFIIIIIIIIIFIFIIFFBBFBFF<F<FFFFFFIFFFFFFFFFF...
19052972  FFBFIFFFBF0FFFFBFFB7B'B0FFIIIIFFIIFFFFFFFBBFB0...
19052973  FIFIIIIIIIFFIIIIIFIIFFFIFIFFFFFIFFFIFFFFFFFFFF...
19052974  IIIIIIIIIIIIIIIIIIFIIIIIIIIIIIIIIIIIIFFFFFFFFF...
19052975  FFIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFFFFFFFFF...
19052976  IIIIIIIIIIIIIIIIIIFIFIIFIIIIIIIIIIIIIFFFFFFFFF...
19052977  ##B<FFFFFBFBBB'B0FFFF<B<F<BBFFFFF<BBBFFFFFBFFF...
19052978  IIIIIIIIIIIIIIIIFIIIIIIIIIIIIIIIIIIIIFFFFFFFFF...
19052979  7FBBFF7FB7B0<7<IIFF77'BBBBBBBFFF<<F<FFFBBB<<<<...
19052980  IIIIIIIIIIIFIIFFIIIIIIIIIIIIIIIIFIIIIFFFFFFFFF...
19052981  ##########FBB''BFB7B'07700BFFBF<<7B<BF<07BBBFF...
19052982  FIIIIIIIIIIIIIIIFFIIIIIFFIIIIIIIFFFIIFFFFFFFFF...
19052983  IIIIIIIIIIIIIIIIFIIIIIIIIIIIIIIIIIIIIFFFFFFFFF...
19052984  IIIIIIIIIIIIIFFFFIIIIIIIIIIIIIIFIIIIIFFFFFFFFF...
19052985  FIIIIIFIIFIIIFIIIFFFIFFIIFFFIFFFIFIFIFFFFFFFFF...
19052986  IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFFFFFFFFF...
19052987  IIIIIFIFIIIFFFFIFIFFFFIIIIIIIIFFIIIIIFFFFFFFFF...
19052988  IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFFFFFFFFF...
19052989  IIIIIIIIIIIIIIIIIIIIIIIIIIIIIFFFIIIIIFFFFFFFFF...
19052990  FIIIFIFFFFIIFFBFBIFIFBFFFIIIFIFBFFFFFFFFFFFFFB...
19052991  IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFFFFFFFFF...
19052992  FIFFBIFFFFB<<7<FBBFIFFFFFIFFFBFBFFBFFFFFFFFBFF...
19052993  IIIIIIIIIIIIIIFIIIIIIIIIIIIIIIFFIIIIIFFFFFFFFF...
19052994  IIIFIIIIIFIIIIIIIIIIIIFIIIIIFFFFIIFIIFFFFFFFFF...
19052995  IIIIIIIFFBFFFBFFIIFFFIIIIIIIIFIIIIIIFFFFFFFFFF...
19052996  FFIFFIIIIFFFIIIIIIIIIIFFFIFFFIIIFFFIFFFFFFFFFF...
19052997  IIIIIIIIIIIIIIIIFIIIIIIFFIIFFIIIIIIIIFFFFFFFFF...
19052998  BIIIIFFFIFFFIIFFFBFIIFFFIIIFFFIIIIIIIFFFFFFFFF...
19052999  BFFFFFFFFFF<IIFFFFFIFBFFBFFFFIIFBIIFFFFF<FBFBF...

[3000 rows x 1 columns]

In [99]:
q21['Q Values'] = q21['Q Values'].apply(asciitodecimal)

/Users/sujay/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [100]:
q21

                                                   Q Values
19050000  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050001  [66, 66, 60, 66, 70, 70, 70, 70, 66, 60, 66, 6...
19050002  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050003  [66, 66, 66, 70, 66, 70, 70, 70, 70, 70, 70, 7...
19050004  [48, 60, 60, 66, 70, 70, 70, 70, 70, 66, 66, 7...
19050005  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050006  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050007  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050008  [66, 66, 66, 70, 70, 70, 66, 70, 70, 70, 70, 7...
19050009  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050010  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050011  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050012  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050013  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050014  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050015  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050016  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050017  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 66, 6...
19050018  [66, 60, 48, 60, 70, 66, 70, 70, 70, 70, 70, 7...
19050019  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050020  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050021  [66, 66, 66, 70, 70, 70, 70, 66, 70, 66, 70, 7...
19050022  [48, 60, 66, 70, 66, 66, 70, 60, 70, 60, 66, 6...
19050023  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050024  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050025  [66, 66, 66, 48, 66, 70, 70, 70, 70, 70, 70, 6...
19050026  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050027  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050028  [66, 66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 7...
19050029  [55, 60, 60, 66, 70, 66, 70, 60, 66, 70, 70, 7...
...                                                     ...
19052970  [66, 70, 70, 73, 70, 70, 70, 70, 70, 66, 66, 7...
19052971  [70, 73, 70, 70, 73, 73, 73, 73, 73, 73, 73, 7...
19052972  [70, 70, 66, 70, 73, 70, 70, 70, 66, 70, 48, 7...
19052973  [70, 73, 70, 73, 73, 73, 73, 73, 73, 73, 70, 7...
19052974  [73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052975  [70, 70, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052976  [73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052977  [35, 35, 66, 60, 70, 70, 70, 70, 70, 66, 70, 6...
19052978  [73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052979  [55, 70, 66, 66, 70, 70, 55, 70, 66, 55, 66, 4...
19052980  [73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052981  [35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 70, 6...
19052982  [70, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052983  [73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052984  [73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052985  [70, 73, 73, 73, 73, 73, 70, 73, 73, 70, 73, 7...
19052986  [73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052987  [73, 73, 73, 73, 73, 70, 73, 70, 73, 73, 73, 7...
19052988  [73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052989  [73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052990  [70, 73, 73, 73, 70, 73, 70, 70, 70, 70, 73, 7...
19052991  [73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052992  [70, 73, 70, 70, 66, 73, 70, 70, 70, 70, 66, 6...
19052993  [73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052994  [73, 73, 73, 70, 73, 73, 73, 73, 73, 70, 73, 7...
19052995  [73, 73, 73, 73, 73, 73, 73, 70, 70, 66, 70, 7...
19052996  [70, 70, 73, 70, 70, 73, 73, 73, 73, 70, 70, 7...
19052997  [73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 7...
19052998  [66, 73, 73, 73, 73, 70, 70, 70, 73, 70, 70, 7...
19052999  [66, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 6...

[3000 rows x 1 columns]

In [101]:
q21['Q Values'] = q21['Q Values'].apply(dectop)

/Users/sujay/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [102]:
q21

                                                   Q Values
19050000  [0.0005011872336272725, 0.0005011872336272725,...
19050001  [0.0005011872336272725, 0.0005011872336272725,...
19050002  [0.0005011872336272725, 0.0005011872336272725,...
19050003  [0.0005011872336272725, 0.0005011872336272725,...
19050004  [0.03162277660168379, 0.001995262314968879, 0....
19050005  [0.0005011872336272725, 0.0005011872336272725,...
19050006  [0.0005011872336272725, 0.0005011872336272725,...
19050007  [0.0005011872336272725, 0.0005011872336272725,...
19050008  [0.0005011872336272725, 0.0005011872336272725,...
19050009  [0.0005011872336272725, 0.0005011872336272725,...
19050010  [0.0005011872336272725, 0.0005011872336272725,...
19050011  [0.0005011872336272725, 0.0005011872336272725,...
19050012  [0.0005011872336272725, 0.0005011872336272725,...
19050013  [0.0005011872336272725, 0.0005011872336272725,...
19050014  [0.0005011872336272725, 0.0005011872336272725,...
19050015  [0.0005011872336272725, 0.0005011872336272725,...
19050016  [0.0005011872336272725, 0.0005011872336272725,...
19050017  [0.0005011872336272725, 0.0005011872336272725,...
19050018  [0.0005011872336272725, 0.001995262314968879, ...
19050019  [0.0005011872336272725, 0.0005011872336272725,...
19050020  [0.0005011872336272725, 0.0005011872336272725,...
19050021  [0.0005011872336272725, 0.0005011872336272725,...
19050022  [0.03162277660168379, 0.001995262314968879, 0....
19050023  [0.0005011872336272725, 0.0005011872336272725,...
19050024  [0.0005011872336272725, 0.0005011872336272725,...
19050025  [0.0005011872336272725, 0.0005011872336272725,...
19050026  [0.0005011872336272725, 0.0005011872336272725,...
19050027  [0.0005011872336272725, 0.0005011872336272725,...
19050028  [0.0005011872336272725, 0.0005011872336272725,...
19050029  [0.00630957344480193, 0.001995262314968879, 0....
...                                                     ...
19052970  [0.0005011872336272725, 0.00019952623149688788...
19052971  [0.00019952623149688788, 0.0001, 0.00019952623...
19052972  [0.00019952623149688788, 0.0001995262314968878...
19052973  [0.00019952623149688788, 0.0001, 0.00019952623...
19052974  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052975  [0.00019952623149688788, 0.0001995262314968878...
19052976  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052977  [0.6309573444801932, 0.6309573444801932, 0.000...
19052978  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052979  [0.00630957344480193, 0.00019952623149688788, ...
19052980  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052981  [0.6309573444801932, 0.6309573444801932, 0.630...
19052982  [0.00019952623149688788, 0.0001, 0.0001, 0.000...
19052983  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052984  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052985  [0.00019952623149688788, 0.0001, 0.0001, 0.000...
19052986  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052987  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052988  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052989  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052990  [0.00019952623149688788, 0.0001, 0.0001, 0.000...
19052991  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052992  [0.00019952623149688788, 0.0001, 0.00019952623...
19052993  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052994  [0.0001, 0.0001, 0.0001, 0.0001995262314968878...
19052995  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052996  [0.00019952623149688788, 0.0001995262314968878...
19052997  [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000...
19052998  [0.0005011872336272725, 0.0001, 0.0001, 0.0001...
19052999  [0.0005011872336272725, 0.00019952623149688788...

[3000 rows x 1 columns]

In [103]:
q21['Q Values'] = q21['Q Values'].apply(maxkeeper)

/Users/sujay/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [104]:
q21

          Q Values
19050000  0.000501
19050001  0.031623
19050002  0.031623
19050003  0.000501
19050004  0.031623
19050005  0.000501
19050006  0.000501
19050007  0.001995
19050008  0.000501
19050009  0.000501
19050010  0.000501
19050011  0.000501
19050012  0.006310
19050013  0.000501
19050014  0.001995
19050015  0.000501
19050016  0.000501
19050017  0.006310
19050018  0.031623
19050019  0.000501
19050020  0.001995
19050021  0.001995
19050022  0.031623
19050023  0.001995
19050024  0.000501
19050025  0.031623
19050026  0.000501
19050027  0.000501
19050028  0.001995
19050029  0.006310
...            ...
19052970  0.000501
19052971  0.001995
19052972  0.251189
19052973  0.000501
19052974  0.000501
19052975  0.000501
19052976  0.000501
19052977  0.630957
19052978  0.000501
19052979  0.251189
19052980  0.000501
19052981  0.630957
19052982  0.000501
19052983  0.000501
19052984  0.000501
19052985  0.000501
19052986  0.000501
19052987  0.000501
19052988  0.000501
19052989  0.000501
19052990  0.000501
19052991  0.000501
19052992  0.006310
19052993  0.000501
19052994  0.000501
19052995  0.000501
19052996  0.000501
19052997  0.000501
19052998  0.001995
19052999  0.001995

[3000 rows x 1 columns]

In [105]:
q21["Q Values"].mean()

0.041092764047644406